apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
  namespace: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: singhpratyush/loklak_server:development
        volumeMounts:
          - mountPath: /loklak_server/data
            name: data-index
        livenessProbe:
          httpGet:
            path: /api/status.json
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 3
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: data-index
        gcePersistentDisk:
          pdName: data-index-disk
          fsType: ext4
